Adding matrix support to the workflow

diff --git a/.github/workflows/build-and-test-orchard-core.yml b/.github/workflows/build-and-test-orchard-core.yml
--- a/.github/workflows/build-and-test-orchard-core.yml
+++ b/.github/workflows/build-and-test-orchard-core.yml
@@ -1,209 +1,221 @@
 ﻿name: Build and Test Orchard Core
 description: Build an Orchard Core solution, then run its tests.
 
-inputs:
-  os:
-    required: false
-    default: ubuntu-latest
-    description: >
-        The name of the OS to run the workflow under, e.g. "ubuntu-latest" or "windows-latest". Defaults to 
-        "ubuntu-latest".
-  build-directory:
-    required: false
-    default: .
-    description: Path to the directory where a solution file can be found.
-  build-verbosity:
-    required: false
-    default: quiet
-    description: Verbosity parameter for dotnet build. Defaults to "quiet".
+on:
+  workflow_call:
+    inputs:
+      # This needs to be stringified JSON because inputs don't support arrays, see 
+      # https://github.community/t/reusable-workflow-with-strategy-matrix/205676/2.
+      machine-types:
+        required: false
+        default: "[\"ubuntu-latest\"]"
+        description: >
+            Stringified JSON array with the name of the type of machine(s) to run the workflow under, e.g.
+            "[\"ubuntu-latest\"]" or "[\"ubuntu-latest\", \"windows-latest\"]". Defaults to "[\"ubuntu-latest\"]".
+      build-directories:
+        required: false
+        default: "[\".\"]"
+        description: >
+          Stringified JSON array with the  path to the directory where a solution file can be found, e.g. 
+          "[\".\", \"NuGetTest\"]". Defaults to "[\".\"]".
+      build-verbosity:
+        required: false
+        default: quiet
+        description: Verbosity parameter for dotnet build. Defaults to "quiet".
 
-runs:
-  using: "composite"
-  steps:
-  - uses: actions/checkout@v2
-    with:
-      submodules: 'recursive'
+jobs:
+  build-and-test:
+    runs-on: ${{ matrix.machine-type }}
+    name: Build and Test
+    strategy:
+      matrix:
+        build-directory: ${{fromJson(inputs.build-directories)}}
+        machine-type: ${{fromJson(inputs.machine-types)}}
+    steps:
+    - uses: actions/checkout@v2
+      with:
+        submodules: 'recursive'
 
-  - name: Set up .NET
-    env:
-      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
-      DOTNET_CLI_TELEMETRY_OPTOUT: "true"
-    uses: actions/setup-dotnet@v1
-    with:
-      dotnet-version: 6.0.*
+    - name: Set up .NET
+      env:
+        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
+        DOTNET_CLI_TELEMETRY_OPTOUT: "true"
+      uses: actions/setup-dotnet@v1
+      with:
+        dotnet-version: 6.0.*
 
-  - name: Build and Static Code Analysis
-    shell: pwsh
-    working-directory: ${{ inputs.build-directory }}
-    run: |
-      npm install pnpm -g
+    - name: Build and Static Code Analysis
+      shell: pwsh
+      working-directory: ${{ inputs.build-directory }}
+      run: |
+        npm install pnpm -g
 
-      if (Test-Path src/Utilities/Lombiq.Gulp.Extensions/Lombiq.Gulp.Extensions.csproj)
-      {
-          dotnet build src/Utilities/Lombiq.Gulp.Extensions/Lombiq.Gulp.Extensions.csproj --configuration Release --verbosity ${{ inputs.build-verbosity }}
-      }
+        if (Test-Path src/Utilities/Lombiq.Gulp.Extensions/Lombiq.Gulp.Extensions.csproj)
+        {
+            dotnet build src/Utilities/Lombiq.Gulp.Extensions/Lombiq.Gulp.Extensions.csproj --configuration Release --verbosity ${{ inputs.build-verbosity }}
+        }
 
-      $buildSwitches = @(
-          '--configuration',
-          'Release',
-          '-warnaserror',
-          '-p:TreatWarningsAsErrors=true',
-          '-p:RunAnalyzersDuringBuild=true',
-          '-nologo',
-          '-consoleLoggerParameters:NoSummary',
-          '-verbosity:${{ inputs.build-verbosity }}'
-      )
+        $buildSwitches = @(
+            '--configuration',
+            'Release',
+            '-warnaserror',
+            '-p:TreatWarningsAsErrors=true',
+            '-p:RunAnalyzersDuringBuild=true',
+            '-nologo',
+            '-consoleLoggerParameters:NoSummary',
+            '-verbosity:${{ inputs.build-verbosity }}'
+        )
 
-      dotnet build (Get-ChildItem *.sln).FullName @buildSwitches
+        dotnet build (Get-ChildItem *.sln).FullName @buildSwitches
 
-  - name: Set up SQL Server
-    shell: pwsh
-    run: |
-      if ($Env:RUNNER_OS -eq "Windows")
-      {
-          choco install sql-server-express --no-progress
-      }
-      else
-      {
-          docker pull mcr.microsoft.com/mssql/server &&
-          docker run --name sql2019 -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Password1!' -p 1433:1433 -d 'mcr.microsoft.com/mssql/server:2019-latest' &&
-          docker exec -u 0 sql2019 bash -c 'mkdir /data; chmod 777 /data -R; chown mssql:root /data'
-      }
+    - name: Set up SQL Server
+      shell: pwsh
+      run: |
+        if ($Env:RUNNER_OS -eq "Windows")
+        {
+            choco install sql-server-express --no-progress
+        }
+        else
+        {
+            docker pull mcr.microsoft.com/mssql/server &&
+            docker run --name sql2019 -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Password1!' -p 1433:1433 -d 'mcr.microsoft.com/mssql/server:2019-latest' &&
+            docker exec -u 0 sql2019 bash -c 'mkdir /data; chmod 777 /data -R; chown mssql:root /data'
+        }
 
-  # Needs to be a separate step, otherwise the Chocolatey installation won't be visible.
-  - name: Wait for SQL Server to start
-    shell: pwsh
-    run: |
-      $maxTryCount = 10
+    # Needs to be a separate step, otherwise the Chocolatey installation won't be visible.
+    - name: Wait for SQL Server to start
+      shell: pwsh
+      run: |
+        $maxTryCount = 10
 
-      for ($i = 1; $i -le $maxTryCount; $i++)
-      {
-          echo "Waiting for SQL Server to start. Attempt $i/$maxTryCount."
+        for ($i = 1; $i -le $maxTryCount; $i++)
+        {
+            echo "Waiting for SQL Server to start. Attempt $i/$maxTryCount."
 
-          if ($Env:RUNNER_OS -eq "Windows")
-          {
-              sqlcmd -b -S .\SQLEXPRESS -Q "SELECT @@SERVERNAME as ServerName" 2>&1>$null
-          }
-          else
-          {
-              sqlcmd -b -U sa -P 'Password1!' -Q "SELECT @@SERVERNAME as ServerName" 2>&1>$null
-          }
+            if ($Env:RUNNER_OS -eq "Windows")
+            {
+                sqlcmd -b -S .\SQLEXPRESS -Q "SELECT @@SERVERNAME as ServerName" 2>&1>$null
+            }
+            else
+            {
+                sqlcmd -b -U sa -P 'Password1!' -Q "SELECT @@SERVERNAME as ServerName" 2>&1>$null
+            }
 
-          if ($?)
-          {
-              echo "SQL Server is successfully started."
-              Exit 0
-          }
+            if ($?)
+            {
+                echo "SQL Server is successfully started."
+                Exit 0
+            }
 
-          if ($i -eq $maxTryCount)
-          {
-              echo "SQL Server couldn't be started."
-              Exit 1
-          }
+            if ($i -eq $maxTryCount)
+            {
+                echo "SQL Server couldn't be started."
+                Exit 1
+            }
 
-          echo "SQL Server is not ready. Waiting 1 second."
-          Start-Sleep -s 1
-      }
+            echo "SQL Server is not ready. Waiting 1 second."
+            Start-Sleep -s 1
+        }
 
-  - name: Set up Azurite via NPM
-    # This needs to run in bash for some reason. Azurite properly starts in PS but still, connections fail.
-    shell: bash
-    run: |
-      npm install -g azurite
-      azurite --silent --location ${{inputs.build-directory}}/azurite --debug ${{inputs.build-directory}}/azurite/debug.log &
+    - name: Set up Azurite via NPM
+      # This needs to run in bash for some reason. Azurite properly starts in PS but still, connections fail.
+      shell: bash
+      run: |
+        npm install -g azurite
+        azurite --silent --location ${{inputs.build-directory}}/azurite --debug ${{inputs.build-directory}}/azurite/debug.log &
 
-  # First, we globally set test configurations using environment variables. Then acquire the list of all test projects
-  # (excluding the two test libraries) and then run each until one fails or all concludes. If a test fails, the output
-  # is sanitized from unnecessary diagnostics messages from chromedriver if the output doesn't already contain
-  # groupings, then it wraps them in '::group::<project name>'. If there are already groupings, then it is not
-  # possible to nest them (https://github.com/actions/runner/issues/802) so that's omitted. The groupings make the
-  # output collapsible region on the Actions web UI. Note that we use bash to output the log using bash to avoid pwsh
-  # wrapping the output to the default buffer width.
-  - name: Tests
-    shell: pwsh
-    working-directory: ${{ inputs.build-directory }}
-    run: |
-      function Configure-Environment($hash) { Set-Item @hash }
+    # First, we globally set test configurations using environment variables. Then acquire the list of all test projects
+    # (excluding the two test libraries) and then run each until one fails or all concludes. If a test fails, the output
+    # is sanitized from unnecessary diagnostics messages from chromedriver if the output doesn't already contain
+    # groupings, then it wraps them in '::group::<project name>'. If there are already groupings, then it is not
+    # possible to nest them (https://github.com/actions/runner/issues/802) so that's omitted. The groupings make the
+    # output collapsible region on the Actions web UI. Note that we use bash to output the log using bash to avoid pwsh
+    # wrapping the output to the default buffer width.
+    - name: Tests
+      shell: pwsh
+      working-directory: ${{ inputs.build-directory }}
+      run: |
+        function Configure-Environment($hash) { Set-Item @hash }
 
-      if ($Env:RUNNER_OS -eq "Windows")
-      {
-          Configure-Environment @{
-              Path = 'Env:\Lombiq_Tests_UI__SqlServerDatabaseConfiguration__ConnectionStringTemplate'
-              Value = 'Server=.\SQLEXPRESS;Database=LombiqUITestingToolbox_{{id}};Integrated Security=True;MultipleActiveResultSets=True;Connection Timeout=60;ConnectRetryCount=15;ConnectRetryInterval=5'
-          }
-      }
-      else
-      {
-          Configure-Environment @{
-              Path = 'Env:\Lombiq_Tests_UI__SqlServerDatabaseConfiguration__ConnectionStringTemplate'
-              Value = 'Server=.;Database=LombiqUITestingToolbox_{{id}};User Id=sa;Password=Password1!;MultipleActiveResultSets=True;Connection Timeout=60;ConnectRetryCount=15;ConnectRetryInterval=5'
-          }
-          Configure-Environment @{
-              Path = 'Env:\Lombiq_Tests_UI__DockerConfiguration__ContainerName'
-              Value = 'sql2019'
-          }
-      }
+        if ($Env:RUNNER_OS -eq "Windows")
+        {
+            Configure-Environment @{
+                Path = 'Env:\Lombiq_Tests_UI__SqlServerDatabaseConfiguration__ConnectionStringTemplate'
+                Value = 'Server=.\SQLEXPRESS;Database=LombiqUITestingToolbox_{{id}};Integrated Security=True;MultipleActiveResultSets=True;Connection Timeout=60;ConnectRetryCount=15;ConnectRetryInterval=5'
+            }
+        }
+        else
+        {
+            Configure-Environment @{
+                Path = 'Env:\Lombiq_Tests_UI__SqlServerDatabaseConfiguration__ConnectionStringTemplate'
+                Value = 'Server=.;Database=LombiqUITestingToolbox_{{id}};User Id=sa;Password=Password1!;MultipleActiveResultSets=True;Connection Timeout=60;ConnectRetryCount=15;ConnectRetryInterval=5'
+            }
+            Configure-Environment @{
+                Path = 'Env:\Lombiq_Tests_UI__DockerConfiguration__ContainerName'
+                Value = 'sql2019'
+            }
+        }
 
-      $tests = dotnet sln list |
-          Select-Object -Skip 2 |
-          Select-String '\.Tests\.' |
-          Select-String -NotMatch 'Lombiq.Tests.UI.csproj' |
-          Select-String -NotMatch 'Lombiq.Tests.csproj' |
-          ? {
-              $result = dotnet test --no-restore --list-tests --verbosity ${{ inputs.build-verbosity }} $_ 2>&1 | Out-String -Width 9999
-              -not [string]::IsNullOrEmpty($result) -and $result.Contains('The following Tests are available')
-          }
+        $tests = dotnet sln list |
+            Select-Object -Skip 2 |
+            Select-String '\.Tests\.' |
+            Select-String -NotMatch 'Lombiq.Tests.UI.csproj' |
+            Select-String -NotMatch 'Lombiq.Tests.csproj' |
+            ? {
+                $result = dotnet test --no-restore --list-tests --verbosity ${{ inputs.build-verbosity }} $_ 2>&1 | Out-String -Width 9999
+                -not [string]::IsNullOrEmpty($result) -and $result.Contains('The following Tests are available')
+            }
 
-      foreach ($test in $tests) {
-          dotnet test -c Release --no-restore --no-build --nologo --logger "trx;LogFileName=test-results.trx" --verbosity ${{ inputs.build-verbosity }} $test 2>&1 >test.out
+        foreach ($test in $tests) {
+            dotnet test -c Release --no-restore --no-build --nologo --logger "trx;LogFileName=test-results.trx" --verbosity ${{ inputs.build-verbosity }} $test 2>&1 >test.out
 
-          if ($?)
-          {
-              echo "Test Successful: $test"
-              continue
-          }
+            if ($?)
+            {
+                echo "Test Successful: $test"
+                continue
+            }
 
-          $needsGrouping = (Select-String '::group::' test.out).Length -eq 0
+            $needsGrouping = (Select-String '::group::' test.out).Length -eq 0
 
-          if ($needsGrouping) { echo "::group::Test Failed: $test" }
+            if ($needsGrouping) { echo "::group::Test Failed: $test" }
 
-          bash -c "cat test.out | grep -v 'Connection refused \[::ffff:127.0.0.1\]' | grep -v 'ChromeDriver was started successfully'"
+            bash -c "cat test.out | grep -v 'Connection refused \[::ffff:127.0.0.1\]' | grep -v 'ChromeDriver was started successfully'"
 
-          if ($needsGrouping) { echo "::endgroup::" }
+            if ($needsGrouping) { echo "::endgroup::" }
 
-          exit 100
-      }
+            exit 100
+        }
 
-  # Note that this would fail under Windows if the path is too long, regardless of LongPathsEnabled, see:
-  # https://github.com/actions/upload-artifact/issues/309. To get around that we merge all FailureDumps into the
-  # solution root. The following two steps need to be always(), so if there's a failure dump it'll be uploaded even if
-  # the tests are ultimately passed after retries. The same is true for the next step as well.
-  - name: Merge FailureDumps
-    shell: pwsh
-    if: always() && hashFiles(format('{0}/test/**/FailureDumps', inputs.build-directory))
-    run: |
-      New-Item -Type Directory "${{inputs.build-directory}}/FailureDumps"
-      Get-ChildItem "${{inputs.build-directory}}/test" -Recurse |
-        ? { $_.Name -eq 'FailureDumps' } |
-        % { $_.GetDirectories() } |
-        % { Move-Item $_.FullName "${{inputs.build-directory}}/FailureDumps/${_.Name}" }
+    # Note that this would fail under Windows if the path is too long, regardless of LongPathsEnabled, see:
+    # https://github.com/actions/upload-artifact/issues/309. To get around that we merge all FailureDumps into the
+    # solution root. The following two steps need to be always(), so if there's a failure dump it'll be uploaded even if
+    # the tests are ultimately passed after retries. The same is true for the next step as well.
+    - name: Merge FailureDumps
+      shell: pwsh
+      if: always() && hashFiles(format('{0}/test/**/FailureDumps', inputs.build-directory))
+      run: |
+        New-Item -Type Directory "${{inputs.build-directory}}/FailureDumps"
+        Get-ChildItem "${{inputs.build-directory}}/test" -Recurse |
+          ? { $_.Name -eq 'FailureDumps' } |
+          % { $_.GetDirectories() } |
+          % { Move-Item $_.FullName "${{inputs.build-directory}}/FailureDumps/${_.Name}" }
 
-  - name: Upload UI testing artifacts
-    uses: actions/upload-artifact@v3
-    # It's always as explained above. We don't need additional conditions, because of the "if-no-files-found" setting.
-    if: always()
-    with:
-      name: ui-test-failure-dump-${{ inputs.build-directory }}-${{ inputs.os }}
-      path: |
-        ${{ inputs.build-directory }}/FailureDumps/
-        test.out
-      if-no-files-found: ignore
+    - name: Upload UI testing artifacts
+      uses: actions/upload-artifact@v3
+      # It's always as explained above. We don't need additional conditions, because of the "if-no-files-found" setting.
+      if: always()
+      with:
+        name: ui-test-failure-dump-${{ inputs.build-directory }}-${{ inputs.machine-type }}
+        path: |
+          ${{ inputs.build-directory }}/FailureDumps/
+          test.out
+        if-no-files-found: ignore
 
-  - name: Test Report
-    uses: phoenix-actions/test-reporting@v8
-    if: success() || failure()
-    with:
-      name: Test Results (${{inputs.build-directory}} ${{inputs.os}})
-      path: '${{inputs.build-directory}}/**/*.trx'
-      reporter: dotnet-trx
-      fail-on-error: 'false'
+    - name: Test Report
+      uses: phoenix-actions/test-reporting@v8
+      if: success() || failure()
+      with:
+        name: Test Results (${{inputs.build-directory}} ${{inputs.machine-type}})
+        path: '${{inputs.build-directory}}/**/*.trx'
+        reporter: dotnet-trx
+        fail-on-error: 'false'
