Fix indentation.

diff --git a/.github/workflows/verify.yml b/.github/workflows/verify.yml
--- a/.github/workflows/verify.yml
+++ b/.github/workflows/verify.yml
@@ -23,52 +23,52 @@ jobs:
       - name: Print PR Title
         run: echo $Env:PULL_REQUEST_TITLE
 
-    - name: Add Scripts
-      run: |
-        $code = @'
-        <#
-        .Synopsis
-        Fails the current step with the provided message. Same as "core.setFailed()" from the official toolkit
-        (https://github.com/actions/toolkit).
-        #>
-        function Set-Failed([Parameter(Mandatory=$True)] [string] $Message)
-        {
-            echo "::error::$Message"
-            exit 1
-        }
+      - name: Add Scripts
+        run: |
+          $code = @'
+          <#
+          .Synopsis
+          Fails the current step with the provided message. Same as "core.setFailed()" from the official toolkit
+          (https://github.com/actions/toolkit).
+          #>
+          function Set-Failed([Parameter(Mandatory=$True)] [string] $Message)
+          {
+              echo "::error::$Message"
+              exit 1
+          }
 
-        <#
-        .Synopsis
-        Returns $True if any item is coming from the pipe.
-        #>
-        function Any-Object([Parameter(Mandatory=$True, ValueFromPipeline = $True)] $Input)
-        {
-            foreach($item in $Input)
-            {
-                return $True
-            }
+          <#
+          .Synopsis
+          Returns $True if any item is coming from the pipe.
+          #>
+          function Any-Object([Parameter(Mandatory=$True, ValueFromPipeline = $True)] $Input)
+          {
+              foreach($item in $Input)
+              {
+                  return $True
+              }
 
-            return $False
-        }
-        '@
+              return $False
+          }
+          '@
 
-        $ProfileDirectory = [System.IO.Path]::GetDirectoryName($Profile)
-        [System.IO.Directory]::CreateDirectory($ProfileDirectory)
+          $ProfileDirectory = [System.IO.Path]::GetDirectoryName($Profile)
+          [System.IO.Directory]::CreateDirectory($ProfileDirectory)
 
-        echo $code >> $Profile
+          echo $code >> $Profile
 
-    - name: Current PR Title Includes Issue Code
-      run: |
-        if ($Env:PULL_REQUEST_TITLE -match '^\s*\w+-\d+\s*:') { exit 0 }
-        Set-Failed 'The pull request is not in the right format. Please start with the issue code followed by a colon e.g. "PROJ-123: My PR Title".'
+      - name: Current PR Title Includes Issue Code
+        run: |
+          if ($Env:PULL_REQUEST_TITLE -match '^\s*\w+-\d+\s*:') { exit 0 }
+          Set-Failed 'The pull request is not in the right format. Please start with the issue code followed by a colon e.g. "PROJ-123: My PR Title".'
 
-    - name: Search Parent Repository for Matching PR
-      run: |
-        $issueCode = $Env:PULL_REQUEST_TITLE -replace '^\s*(\w+-\d+)\s*:.*$', '$1'
+      - name: Search Parent Repository for Matching PR
+        run: |
+          $issueCode = $Env:PULL_REQUEST_TITLE -replace '^\s*(\w+-\d+)\s*:.*$', '$1'
 
-        $url = 'https://api.github.com/repos/Lombiq/Open-Source-Orchard-Core-Extensions/pulls?state=open&per_page=100'
-        $titles = curl -H 'Accept: application/vnd.github.v3+json' $url | ConvertFrom-Json | % { $_.title }
+          $url = 'https://api.github.com/repos/Lombiq/Open-Source-Orchard-Core-Extensions/pulls?state=open&per_page=100'
+          $titles = curl -H 'Accept: application/vnd.github.v3+json' $url | ConvertFrom-Json | % { $_.title }
 
-        $lookFor = "${issueCode}:"
-        if ($titles | ? { $_ -and $_.Contains($lookFor) } | Any-Object) { exit 0 }
-        Set-Failed "Couldn't find an Open-Source-Orchard-Core-Extensions pull request whose title starts with `"$lookFor`"."
+          $lookFor = "${issueCode}:"
+          if ($titles | ? { $_ -and $_.Contains($lookFor) } | Any-Object) { exit 0 }
+          Set-Failed "Couldn't find an Open-Source-Orchard-Core-Extensions pull request whose title starts with `"$lookFor`"."
